# Generated by Django 5.0.7 on 2024-07-21 15:00

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Resposta', 'verbose_name_plural': 'Respostas'},
        ),
        migrations.RemoveField(
            model_name='form',
            name='text',
        ),
        migrations.AddField(
            model_name='form',
            name='title',
            field=models.CharField(default=None, max_length=255, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='answered_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Respondido em'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_answers', to='instruments.choice', verbose_name='Alternativa'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='instruments.question', verbose_name='Questão'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Correta'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='instruments.question', verbose_name='Questão'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Alternativa'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='weight',
            field=models.FloatField(default=0.0, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='question',
            name='form',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='instruments.form', verbose_name='Formulário'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Enunciado'),
        ),
        migrations.AlterModelTable(
            name='answer',
            table='answers',
        ),
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_sheet_answers', to='instruments.choice')),
                ('user', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Gabarito',
                'verbose_name_plural': 'Gabaritos',
                'db_table': 'answer_sheets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_sheet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sheet_answers', to='instruments.answersheet', verbose_name='Gabarito'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('answer_sheet', 'question')},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='form',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
    ]
