# Generated by Django 5.0.7 on 2024-07-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_alter_answer_options_remove_form_text_form_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='description',
            field=models.TextField(default=None, max_length=800, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=800, verbose_name='Enunciado'),
        ),
    ]
