# Generated by Django 5.0.7 on 2024-10-26 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_form_description_alter_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_sheet_answers', to='instruments.form'),
        ),
    ]
