# Generated by Django 5.0.9 on 2025-02-11 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0004_alter_answersheet_form'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['pk'], 'verbose_name': 'Alternativa', 'verbose_name_plural': 'Alternativas'},
        ),
        migrations.AddField(
            model_name='form',
            name='type_form',
            field=models.CharField(choices=[('1', 'Objetiva'), ('2', 'Concordância/Discordância')], default='1', max_length=1, verbose_name='Tipo de resposta'),
            preserve_default=False,
        ),
    ]
