# Generated by Django 5.0.11 on 2025-02-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0005_alter_choice_options_form_type_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='type_form',
            field=models.CharField(choices=[('1', 'Objetiva'), ('2', 'Concordância/Discordância'), ('3', 'Dicotômica')], max_length=1, verbose_name='Tipo de resposta'),
        ),
    ]
