# Generated by Django 5.0.9 on 2025-02-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0006_alter_form_type_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('1', 'Objetiva'), ('2', 'Multipla escolha')], default='1', max_length=1, verbose_name='Tipo de resposta'),
        ),
    ]
