# Generated by Django 5.0.9 on 2025-02-11 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lembrete', 'verbose_name_plural': 'Lembretes'},
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Completo')], default='pending', max_length=20),
        ),
    ]
