# Generated by Django 5.0.9 on 2025-01-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_diabete_user_diabetes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='altura',
            field=models.IntegerField(blank=True, null=True, verbose_name='altura'),
        ),
    ]
