# Generated by Django 5.0.9 on 2025-01-11 18:42

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlycemiaLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('measurement_time', models.DateTimeField(auto_now_add=True, verbose_name='Horário')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('user', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Medição de Glicemia',
                'verbose_name_plural': 'Medições de Glicemia',
                'db_table': 'glycemia_log',
                'ordering': ['-measurement_time'],
            },
        ),
    ]
