# Generated by Django 5.0.9 on 2024-11-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category_postpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='subtitle',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
