# Generated by Django 5.0.11 on 2025-04-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_postpage_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='url_video',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Video'),
        ),
    ]
